# Generated by Django 2.0.3 on 2019-04-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteerprovider',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='volunteerprovider',
            name='organization',
        ),
    ]
