# Generated by Django 2.0.3 on 2019-04-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190430_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerevent',
            old_name='decription',
            new_name='desc',
        ),
    ]
