# Generated by Django 2.0.3 on 2019-04-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190430_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='eventcity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.EventState'),
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='location_city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.EventCity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerevent',
            name='location_state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.EventState'),
            preserve_default=False,
        ),
    ]
