# Generated by Django 2.0.3 on 2019-05-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_volunteerpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerEventSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.VolunteerEvent')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Volunteer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='volunteereventsignup',
            unique_together={('volunteer', 'event')},
        ),
    ]
