# Generated by Django 2.0.3 on 2019-05-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190501_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.EventState', unique=True),
        ),
        migrations.AlterField(
            model_name='eventstate',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(default='None', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rest_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_email',
            field=models.EmailField(default='None@none.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_token',
            field=models.CharField(default='None', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteerprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
