# Generated by Django 2.0.3 on 2019-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190502_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_token',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
