# Generated by Django 2.0.3 on 2019-05-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_donationevent_userdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonation',
            name='charge',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
