# Generated by Django 2.0.3 on 2019-05-14 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190511_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVolunteerInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVolunteerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.EventCity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.EventCountry')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.EventState')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVolunteerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='uservolunteerskill',
            name='volunteer_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.VolunteerSkill'),
        ),
        migrations.AddField(
            model_name='uservolunteerlocation',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ZipCode'),
        ),
        migrations.AddField(
            model_name='uservolunteerinterest',
            name='volunteer_interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.VolunteerInterest'),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.EventCountry'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='uservolunteerskill',
            unique_together={('user', 'volunteer_skill')},
        ),
        migrations.AlterUniqueTogether(
            name='uservolunteerlocation',
            unique_together={('user', 'city', 'state', 'country', 'zip_code')},
        ),
        migrations.AlterUniqueTogether(
            name='uservolunteerinterest',
            unique_together={('user', 'volunteer_interest')},
        ),
    ]
