# Generated by Django 2.0.3 on 2019-05-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190517_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerinterest',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerskill',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
