# Generated by Django 2.0.3 on 2019-05-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_volunteerevent_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.DonationEvent'),
        ),
    ]
